version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Pass the Neon DB connection string as an environment variable
      - NEON_DATABASE_URL=${NEON_DATABASE_URL}
    restart: always
    # Healthcheck to ensure the application is running correctly
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
